#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr last
#' @importFrom fs path_abs
#' @importFrom fs path_file
#' @importFrom httr2 req_auth_aws_v4
#' @importFrom httr2 req_auth_basic
#' @importFrom httr2 req_auth_bearer_token
#' @importFrom httr2 req_body_file
#' @importFrom httr2 req_body_form
#' @importFrom httr2 req_body_json
#' @importFrom httr2 req_body_json_modify
#' @importFrom httr2 req_body_multipart
#' @importFrom httr2 req_body_raw
#' @importFrom httr2 req_cache
#' @importFrom httr2 req_cookie_preserve
#' @importFrom httr2 req_cookies_set
#' @importFrom httr2 req_dry_run
#' @importFrom httr2 req_error
#' @importFrom httr2 req_headers
#' @importFrom httr2 req_headers_redacted
#' @importFrom httr2 req_method
#' @importFrom httr2 req_oauth
#' @importFrom httr2 req_oauth_auth_code
#' @importFrom httr2 req_oauth_bearer_jwt
#' @importFrom httr2 req_oauth_client_credentials
#' @importFrom httr2 req_oauth_device
#' @importFrom httr2 req_oauth_password
#' @importFrom httr2 req_oauth_refresh
#' @importFrom httr2 req_oauth_token_exchange
#' @importFrom httr2 req_options
#' @importFrom httr2 req_perform
#' @importFrom httr2 req_perform_connection
#' @importFrom httr2 req_perform_iterative
#' @importFrom httr2 req_perform_parallel
#' @importFrom httr2 req_perform_promise
#' @importFrom httr2 req_perform_sequential
#' @importFrom httr2 req_perform_stream
#' @importFrom httr2 req_progress
#' @importFrom httr2 req_proxy
#' @importFrom httr2 req_retry
#' @importFrom httr2 req_template
#' @importFrom httr2 req_throttle
#' @importFrom httr2 req_timeout
#' @importFrom httr2 req_url
#' @importFrom httr2 req_url_path
#' @importFrom httr2 req_url_path_append
#' @importFrom httr2 req_url_query
#' @importFrom httr2 req_url_relative
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_verbose
#' @importFrom httr2 request
#' @importFrom httr2 resp_body_html
#' @importFrom httr2 resp_body_json
#' @importFrom httr2 resp_body_raw
#' @importFrom httr2 resp_body_string
#' @importFrom httr2 resp_body_xml
#' @importFrom httr2 resp_check_content_type
#' @importFrom httr2 resp_check_status
#' @importFrom httr2 resp_content_type
#' @importFrom httr2 resp_date
#' @importFrom httr2 resp_encoding
#' @importFrom httr2 resp_has_body
#' @importFrom httr2 resp_header
#' @importFrom httr2 resp_header_exists
#' @importFrom httr2 resp_headers
#' @importFrom httr2 resp_is_error
#' @importFrom httr2 resp_link_url
#' @importFrom httr2 resp_raw
#' @importFrom httr2 resp_request
#' @importFrom httr2 resp_retry_after
#' @importFrom httr2 resp_status
#' @importFrom httr2 resp_status_desc
#' @importFrom httr2 resp_stream_aws
#' @importFrom httr2 resp_stream_is_complete
#' @importFrom httr2 resp_stream_lines
#' @importFrom httr2 resp_stream_raw
#' @importFrom httr2 resp_stream_sse
#' @importFrom httr2 resp_url
#' @importFrom httr2 resp_url_path
#' @importFrom httr2 resp_url_queries
#' @importFrom httr2 resp_url_query
#' @importFrom httr2 response
#' @importFrom httr2 response_json
#' @importFrom httr2 resps_data
#' @importFrom httr2 resps_failures
#' @importFrom httr2 resps_requests
#' @importFrom httr2 resps_successes
#' @importFrom purrr list_transpose
#' @importFrom rappdirs user_cache_dir
#' @importFrom tibble as_tibble
## usethis namespace: end
NULL
